### PR TITLE
add compatibility with channels 3

### PR DESCRIPTION
**Pull request by jherencia**

### CODE REVIEW

**Comment by fabienheureux** [comment]
@jherencia I just came accross this PR, after I opened one.
Would you prefer to bring the changes into yours ? Or should I rather merge yours into mine ? 

Cf https://github.com/graphql-python/graphql-ws/pull/76

**Comment by jherencia** [comment]
@fabienheureux Whatever you prefer :)

**Comment by fabienheureux** [comment]
https://github.com/graphql-python/graphql-ws/pull/76 this PR has been approved and includes your changes, yours can be closed I guess 🤷

**Comment by jherencia** [comment]
Perfect, great news!

**Comment by fabienheureux** [comment]
I got admin access to the repo, I will release a new version this week inculding these changes 🥳

**Pull request closed without merging**
