### PR TITLE
add a gevent websocket server (WIP)

### PR DESCRIPTION
**Pull request by colanconnon**
starting on a websocket server using gevent. This requires some changes to core i am also working on

### CODE REVIEW

**Comment by syrusakbary** [comment]
Great work so far @colanconnon .
Would love to add this back into the package. Let me know when is ready to review :)

**Comment by colanconnon** [comment]
@syrusakbary I will clean this up this weekend

**Comment by colanconnon** [comment]
@syrusakbary this is in a better state now with more parody to the original implementation

**Comment by syrusakbary** [comment]
It looks great. Merging :)

**Pull request merged**
