### PR TITLE
Update django_channels.py

### PR DESCRIPTION
**Pull request by ian13456**
Fixed unresolved import.

### CODE REVIEW

**Comment by messa** [comment]
:+1: Looks like the module was renamed in https://github.com/django/channels/commit/4f320745278ab45ac52f9d622dda51f2f45bffc8 as part of major rewrite for channels 2.0.0.

**Comment by jbovenschen** [comment]
@syrusakbary Is there any change this could be merged? This is the only thing which is missing to use graphql-ws as socket server for channels v2

**Comment by Duesterwald** [comment]
In order to keep backwards compatibility, I would suggest to use

`
try:
  from channels.generic.websocket import JsonWebsocketConsumer
except ImportError:
  from channels.generic.websockets import JsonWebsocketConsumer
`


> Fixed unresolved import.

**Comment by SmileyChris** [comment]
#23 will provide a proper django channels 2 solution, leaving the current solution "valid" for channels 1

**Pull request closed without merging**
